# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 411ea07e4b620bff7e5a0a2eb4583d68d669937f32b8a749c0c5f74738cf4c92f0ed1f902ccc2111a0b011c966b1a4d12a313f1941d377f6494307780c81bd38

test:
  secret_key_base: e77cb51a148df9f04558367fc6a14193a4f766f163b9c1dff47590f7abd8ebfcf10cde1904e087e3e832a351dd9f70cf11913c78eb618222d86b2f170afa01ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
